export const questions = {
  "American Football": [
    {
      question: "How do teams advance to the playoffs in the NFL?",
      a1: "By winning the most games in the first half of the season.",
      a2: "By finishing the season with the most points scored overall.",
      a3: "By having the best records in their division or conference.",
      a4: "By being selected randomly by a panel.",
      correct: 3,
    },
    {
      question:
        "What are the different types of penalties in football, and how do they affect the game?",
      a1: "Penalties result in the loss of yards or automatic first downs.",
      a2: "Penalties are calls made to extend play time.",
      a3: "Penalties are only given to the team that scores.",
      a4: "Penalties are optional and rarely enforced.",
      correct: 1,
    },
    {
      question: "What is a quarterback's role on the team?",
      a1: "The quarterback plays only on defense.",
      a2: "The quarterback leads the offense, calls plays, and passes or hands off the ball.",
      a3: "The quarterback's main role is to score field goals.",
      a4: "The quarterback is responsible for kicking the ball.",
      correct: 2,
    },
    {
      question: "How long is an American football game, and how is it divided?",
      a1: "90 minutes, divided into two halves.",
      a2: "60 minutes, divided into four quarters.",
      a3: "45 minutes, divided into two halves.",
      a4: "120 minutes, divided into four quarters",
      correct: 2,
    },
    {
      question:
        "How many players are on the field for each team during a game?",
      a1: "5 players.",
      a2: "7 players.",
      a3: "11 players.",
      a4: "15 players.",
      correct: 3,
    },
    {
      question:
        "What is a down, and how does the down system work in football?",
      a1: "A down is when a player drops the ball.",
      a2: "A down is a penalty for breaking the rules.",
      a3: "A down is when the game is paused for a timeout.",
      a4: "A down is a play attempt, with four downs to advance 10 yards.",
      correct: 4,
    },
    {
      question: "What is a field goal, and how many points does it score?",
      a1: "A field goal is when the ball is kicked through the opponent's goalposts; worth 3 points.",
      a2: "A field goal is when the ball is thrown over the end zone; worth 3 points.",
      a3: "A field goal is when the ball is kicked through the opponent's goalposts; worth 3 points.",
      a4: "A field goal is a defensive move; worth 0 points.",
      correct: 1,
    },
    {
      question:
        "What is a safety in football, and how many points is it worth?",
      a1: "When a defensive player kicks the ball; worth 2 points.",
      a2: "When a player intercepts the ball; worth 3 points.",
      a3: "When a player fumbles the ball in the end zone; worth 1 point.",
      a4: "When the defense tackles an offensive player in their own end zone; worth 2 points.",
      correct: 4,
    },
    {
      question: "What is a two-point conversion?",
      a1: "A penalty that gives the other team 2 points.",
      a2: "A scoring attempt made after a touchdown by running or passing the ball into the end zone again.",
      a3: "When a field goal is worth 2 points.",
      a4: "A play used to stop the clock for 2 minutes.",
      correct: 2,
    },
    {
      question:
        "How many points is a typical extra point kick worth after a touchdown?",
      a1: "2 points.",
      a2: "3 points.",
      a3: "1 point.",
      a4: "4 points.",
      correct: 3,
    },
  ],
  "Countries of the World": [
    {
      question: "What is the largest country by land area?",
      a1: "China",
      a2: "United States",
      a3: "Russia",
      a4: "Canada",
      correct: 3,
    },
    {
      question: "Which country is known for being the birthplace of democracy?",
      a1: "Greece",
      a2: "United States of America",
      a3: "England",
      a4: "South Africa",
      correct: 1,
    },
    {
      question: "Which country is the smallest by land area?",
      a1: "Monaco",
      a2: "Vatican City",
      a3: "San Marino",
      a4: "Liechtenstein",
      correct: 2,
    },
    {
      question: "Which country has the most UNESCO World Heritage Sites?",
      a1: "Peru",
      a2: "Italy",
      a3: "Greece",
      a4: "China",
      correct: 2,
    },
    {
      question: "Which country has the longest coastline in the world?",
      a1: "Chile",
      a2: "Colombia",
      a3: "Alaska",
      a4: "Canada",
      correct: 4,
    },
    {
      question: "Which country is known as the 'Land of the Rising Sun'?",
      a1: "Japan",
      a2: "Venezuela",
      a3: "India",
      a4: "Mongolia",
      correct: 1,
    },
    {
      question: "Which country is home to the Andes mountain range?",
      a1: "Chile",
      a2: "Ecuador",
      a3: "Peru",
      a4: "Mexico",
      correct: 3,
    },
    {
      question: "Which continent has the most countries?",
      a1: "Europe",
      a2: "Africa",
      a3: "Asia",
      a4: " North America",
      correct: 2,
    },
    {
      question: "Which Middle Eastern country is the leading producer of oil?",
      a1: "Iraq",
      a2: "UAE",
      a3: "Saudi Arabia",
      a4: "Iran",
      correct: 3,
    },
    {
      question: "What is the capital of Australia?",
      a1: "Canberra",
      a2: "Sydney",
      a3: "Melbourne",
      a4: "Brisbane",
      correct: 1,
    },
  ],
  "Soccer Facts": [
    {
      question: "Which country has won the most FIFA World Cup titles?",
      a1: "Argentina",
      a2: "Brazil",
      a3: "Italy",
      a4: "England",
      correct: 2,
    },
    {
      question: "Who is the all-time top scorer in FIFA World Cup history?",
      a1: "Pelé",
      a2: "Lionel Messi",
      a3: "Cristiano Ronaldo",
      a4: "Miroslav Klose",
      correct: 4,
    },
    {
      question: "Which soccer player is known as 'The King of Football'?",
      a1: "Diego Maradona",
      a2: "Zinedine Zidane",
      a3: "Pelé",
      a4: "Lionel Messi",
      correct: 3,
    },
    {
      question: "Which club has won the most UEFA Champions League titles?",
      a1: "Real Madrid",
      a2: "Barcelona",
      a3: "Inter Milan",
      a4: "Manchester United",
      correct: 1,
    },
    {
      question:
        "Which soccer competition is held every four years and features national teams?",
      a1: "FIFA World Cup",
      a2: "FA Cup",
      a3: "UEFA Champions League",
      a4: "Copa Libertadores",
      correct: 1,
    },
    {
      question: "Which country hosted the first FIFA World Cup?",
      a1: "Greece",
      a2: "Uruguay",
      a3: "Italy",
      a4: "Brazil",
      correct: 2,
    },
    {
      question: "Who won the Ballon d'Or the most times?",
      a1: "Pelé",
      a2: "Neymar Jr",
      a3: "Cristiano Ronaldo",
      a4: "Lionel Messi",
      correct: 4,
    },
    {
      question:
        "What is the maximum number of players a team can have on the field in soccer?",
      a1: "7",
      a2: "22",
      a3: "11",
      a4: "13",
      correct: 3,
    },
    {
      question: "What is a 'hat trick' in soccer?",
      a1: "Scoring two goals",
      a2: "Scoring three goals in a game",
      a3: "Winning three games in a row",
      a4: "Making three saves in a match",
      correct: 2,
    },
    {
      question: "Which English club is nicknamed 'The Red Devils'?",
      a1: "Manchester United",
      a2: "Arsenal",
      a3: "Chelsea",
      a4: "Liverpool",
      correct: 1,
    },
  ],
  "Basketball": [
    {
      question: "Who is considered the greatest basketball player of all time?",
      a1: "Lebron James",
      a2: "Larry Bird",
      a3: "Magic Johnson",
      a4: "Michael Jordan",
      correct: 4,
    },
    {
      question: "Which team has won the most NBA championships?",
      a1: "Boston Celtics",
      a2: "Miami Heat",
      a3: "Los Angeles Lakers",
      a4: "Golden State Warriors",
      correct: 1,
    },
    {
      question: "How many points is a free throw worth?",
      a1: "3",
      a2: "2",
      a3: "1",
      a4: "0.5",
      correct: 3,
    },
    {
      question:
        "Which player holds the record for most career points in the NBA?",
      a1: "Kareem Abdul-Jabbar",
      a2: "Karl Malone",
      a3: "Lebron James",
      a4: "Derrick Rose",
      correct: 3,
    },
    {
      question: "Who was known as “The Black Mamba”?",
      a1: "Tim Duncan",
      a2: "Shaquille O'Neal",
      a3: "Kevin Durant",
      a4: "Kobe Bryant",
      correct: 4,
    },
    {
      question: "What is the height of a standard basketball hoop?",
      a1: "15 feet",
      a2: "10 feet",
      a3: "9 feet",
      a4: "6 feet",
      correct: 2,
    },
    {
      question:
        "Which country won the gold medal in men's basketball at the 1992 Summer Olympics",
      a1: "U.S.A.",
      a2: "Spain",
      a3: "Greece",
      a4: "Italy",
      correct: 1,
    },
    {
      question:
        "How many players from each team are on the basketball court at one time?",
      a1: "7 players",
      a2: "10 players",
      a3: "5 players",
      a4: "6 players",
      correct: 3,
    },
    {
      question: "Which NBA player is famous for his 'Skyhook' shot?",
      a1: "Lebron James",
      a2: "Kareem Abdul-Jabbar",
      a3: "Wilt Chamberlain",
      a4: "Magic Johnson",
      correct: 2,
    },
    {
      question: "What is the duration of an NBA game?",
      a1: "60 minutes",
      a2: "48 minutes",
      a3: "45 minutes",
      a4: "55 minutes",
      correct: 2,
    },
  ],
  "Famous Wars": [
    {
      question: "Which war is known as 'The Great War'?",
      a1: "World War II",
      a2: "100 years War",
      a3: "World War I",
      a4: "Napoleonic Wars",
      correct: 3,
    },
    {
      question: "Who fought in the American Civil War?",
      a1: "North Mexico and South Mexico",
      a2: "Britain and France",
      a3: "China and Hong Kong",
      a4: "The Union and the Confederacy",
      correct: 4,
    },
    {
      question: "What event started World War I?",
      a1: "The assasination of Archduke Franz Ferdinand",
      a2: "The building of the Berlin Wall",
      a3: "The bombing of Pearl Harbor",
      a4: "The Treaty of Versailles",
      correct: 1,
    },
    {
      question: "Which two countries were primarily involved in the Cold War?",
      a1: "Britain and France",
      a2: "United States and the Soviet Union",
      a3: "China and Japan",
      a4: "Soviet Union and China",
      correct: 2,
    },
    {
      question: "What year did World War II end?",
      a1: "1939",
      a2: "1942",
      a3: "1940",
      a4: "1945",
      correct: 4,
    },
    {
      question: "Which war was fought between the United States and Vietnam?",
      a1: "Seven Years War",
      a2: "Gulf War",
      a3: "Vietnam War",
      a4: "Viet Cong War",
      correct: 3,
    },
    {
      question: "What was the longest war in U.S. history?",
      a1: "War on Terror",
      a2: "Vietnam War",
      a3: "100 years War",
      a4: "Civil War",
      correct: 1,
    },
    {
      question: "Which war began with the invasion of Poland?",
      a1: "World War I",
      a2: "The Franco-Prussian Wars",
      a3: "Napoleonic Wars",
      a4: "World War II",
      correct: 4,
    },
    {
      question: "Who fought in the Crimean War?",
      a1: "Britain and Germany",
      a2: "France, Britain, and Russia",
      a3: "France and Poland",
      a4: "Prussia, Italy, and Britain",
      correct: 2,
    },
    {
      question: "In which war was the Battle of Waterloo fought?",
      a1: "Napoleonic Wars",
      a2: "American Civil War",
      a3: "Franco-Priussian Wars",
      a4: "The Seven Years War",
      correct: 1,
    },
  ],
  "Historical Figures": [
    {
      question: "Who was the first President of the United States?",
      a1: "Abraham Lincoln",
      a2: "John Adams",
      a3: "Thomas Jefferson",
      a4: "George Washington",
      correct: 4,
    },
    {
      question:
        "Who led the Indian independence movement against British rule?",
      a1: "Jawaharlal Nehru",
      a2: "Mahatma Gandhi",
      a3: "Subhas Chandra Bose",
      a4: "Indira Gandhi",
      correct: 2,
    },
    {
      question: "Who was the first woman to win a Nobel Prize?",
      a1: "Rosa Parks",
      a2: "Marie Curie",
      a3: "Harriet Tubman",
      a4: "Eleanor Roosevelt",
      correct: 2,
    },
    {
      question:
        "Who was the famous British Prime Minister during World War II?",
      a1: "Margaret Thatcher",
      a2: "Tony Blair",
      a3: "Winston Churchill",
      a4: "Neville Chamberlain",
      correct: 3,
    },
    {
      question: "Which Roman leader was assassinated on the Ides of March?",
      a1: "Brutus",
      a2: "Nero",
      a3: "Aristotle",
      a4: "Julius Caesar",
      correct: 4,
    },
    {
      question: "Who was known as the 'Maid of Orléans'?",
      a1: "Elizabeth I",
      a2: "Joan of Arc",
      a3: "Marie Antoinette",
      a4: "Catherine the Great",
      correct: 2,
    },
    {
      question: "Which explorer introduced the New World to Europe",
      a1: "Christopher Colombus",
      a2: "Ferdinand Magellan",
      a3: "Hernan Cortes",
      a4: "Marco Polo",
      correct: 1,
    },
    {
      question: "Who led the Civil Rights Movement in the United States?",
      a1: "Malcolm X",
      a2: "Martin Luther King Jr.",
      a3: "Rosa Parks",
      a4: "Frederick Douglas",
      correct: 2,
    },
    {
      question:
        "Who was the British Queen that reigned for over 60 years during the 19th century?",
      a1: "Queen Anne",
      a2: "Queen Elizabeth I",
      a3: "Queen Victoria",
      a4: "Queen Mary",
      correct: 3,
    },
    {
      question: "Who was the first Emperor of Rome?",
      a1: "Caligula",
      a2: "Julius Caesar",
      a3: "Augustus",
      a4: "Nero",
      correct: 3,
    },
  ],
  "US History": [
    {
      question: "Who wrote the Declaration of Independence?",
      a1: "Benjamin Franklin",
      a2: "Thomas Jefferson",
      a3: "George Washington",
      a4: "John Locke",
      correct: 2,
    },
    {
      question: "Which war gave the United States independence from Britain?",
      a1: "The American Civil War",
      a2: "The War of 1812",
      a3: "The Mexican-American War",
      a4: "The Revolutionary War",
      correct: 4,
    },
    {
      question:
        "What year did the United States land the first man on the moon?",
      a1: "1967",
      a2: "1968",
      a3: "1970",
      a4: "1969",
      correct: 4,
    },
    {
      question: "Who was the U.S. President during the Civil War?",
      a1: "Ulysses S. Grant",
      a2: "Andrew Johnson",
      a3: "Abraham Lincoln",
      a4: "Thomas Jefferson",
      correct: 3,
    },
    {
      question: "What was the primary cause of the U.S. Civil War?",
      a1: "Slavery and states' rights",
      a2: "Disputes over taxation",
      a3: "Expansion of the United States",
      a4: "Religious differences",
      correct: 1,
    },
    {
      question: "Which document freed the slaves during the Civil War?",
      a1: "The Gettysburg Address",
      a2: "The Bill of Rights",
      a3: "Emancipation Proclamation",
      a4: "The 13th Ammendment",
      correct: 3,
    },
    {
      question: "Which U.S. President resigned due to the Watergate scandal?",
      a1: "Gerald Ford",
      a2: "Bill Clinton",
      a3: "Ronald Reagan",
      a4: "Richard Nixon",
      correct: 4,
    },
    {
      question: "What year did the United States enter World War II?",
      a1: "1939",
      a2: "1941",
      a3: "1943",
      a4: "1940",
      correct: 2,
    },
    {
      question: "Which amendment gave women the right to vote?",
      a1: "15th Ammendment",
      a2: "19th Ammendment",
      a3: "3rd Ammendment",
      a4: "16th Ammendment",
      correct: 2,
    },
    {
      question: "What was the major economic event of the 1930s?",
      a1: "The Great Recession",
      a2: "The Industrial Revolution",
      a3: "The Great Depression",
      a4: "The Gilded Age",
      correct: 3,
    },
  ],
  "Bands and Artists": [
    {
      question: "Which band is known for hits like 'Hey Jude' and 'Let It Be'?",
      a1: "Queen",
      a2: "The Clash",
      a3: "The Beatles",
      a4: "The Rolling Stones",
      correct: 3,
    },
    {
      question: "Who is known as the 'King of Pop'?",
      a1: "Elvis Presley",
      a2: "Michael Jackson",
      a3: "Morrisey",
      a4: "Prince",
      correct: 2,
    },
    {
      question: "Which band is known for the album Dark Side of the Moon?",
      a1: "Pink Floyd",
      a2: "Pearl Jam",
      a3: "Eagles",
      a4: "The Who",
      correct: 1,
    },
    {
      question: "Who is the lead singer of the rock band Queen?",
      a1: "Freddie Mercury",
      a2: "Axl Rose",
      a3: "Prince",
      a4: "Mick Jagger",
      correct: 1,
    },
    {
      question: "Which artist is famous for the song 'Purple Haze'?",
      a1: "Prince",
      a2: "Jimi Hendrix",
      a3: "Elton John",
      a4: "Elvis Presley",
      correct: 2,
    },
    {
      question: "Which band is known for the song 'Smells Like Teen Spirit'?",
      a1: "Fleetwood Mac",
      a2: "Linkin Park",
      a3: "Green Day",
      a4: "Nirvana",
      correct: 4,
    },
    {
      question:
        "Which female artist is famous for hits like 'Rolling in the Deep' and 'Hello'?",
      a1: "Lionel Richie",
      a2: "Lady Gaga",
      a3: "Adele",
      a4: "Taylor Swift",
      correct: 3,
    },
    {
      question: "Who was the lead guitarist of The Rolling Stones?",
      a1: "Eric Clapton",
      a2: "Keith Richards",
      a3: "Dave Grohl",
      a4: "Slash",
      correct: 2,
    },
    {
      question: "Which artist released the album Lemonade?",
      a1: "Taylor Swift",
      a2: "Gucci Mane",
      a3: "Mariah Carey",
      a4: "Beyonce",
      correct: 4,
    },
    {
      question: "Who is the lead singer of U2?",
      a1: "Bono",
      a2: "Axl Rose",
      a3: "Sting",
      a4: "Morrisey",
      correct: 1,
    },
  ],
  "Movie Characters": [
    {
      question: "Which character said 'I'll be back' in *The Terminator*?",
      a1: "John Connor",
      a2: "Sarah Connor",
      a3: "The Terminator",
      a4: "Kyle Reese",
      correct: 3,
    },
    {
      question: "Which superhero is known for his vibranium shield?",
      a1: "Iron Man",
      a2: "Thor",
      a3: "Captain America",
      a4: "Black Panther",
      correct: 3,
    },
    {
      question:
        "Which character is famous for saying 'May the Force be with you'?",
      a1: "Luke Skywalker",
      a2: "Han Solo",
      a3: "Obi-Wan Kenobi",
      a4: "Yoda",
      correct: 1,
    },
    {
      question: "Who is the leader of the Avengers?",
      a1: "Thor",
      a2: "Captain America",
      a3: "Iron Man",
      a4: "Hulk",
      correct: 2,
    },
    {
      question: "Which character is famous for saying 'Why so serious?'",
      a1: "The Joker",
      a2: "Harley Quinn",
      a3: "Batman",
      a4: "Two-Face",
      correct: 1,
    },
    {
      question:
        "Which character is known for the catchphrase 'Life is like a box of chocolates'?",
      a1: "Forrest Gump",
      a2: "Tom Hanks",
      a3: "Andy Dufresne",
      a4: "Woody",
      correct: 1,
    },
    {
      question: "Who is the main antagonist in *The Lion King*?",
      a1: "Simba",
      a2: "Scar",
      a3: "Mufasa",
      a4: "Zazu",
      correct: 2,
    },
    {
      question:
        "Which character from *Harry Potter* is known as 'The Boy Who Lived'?",
      a1: "Ron Weasley",
      a2: "Harry Potter",
      a3: "Neville Longbottom",
      a4: "Draco Malfoy",
      correct: 2,
    },
    {
      question: "Who says 'There's no place like home' in *The Wizard of Oz*?",
      a1: "Dorothy",
      a2: "The Scarecrow",
      a3: "The Tin Man",
      a4: "The Cowardly Lion",
      correct: 1,
    },
    {
      question:
        "Which character famously exclaimed, 'To infinity and beyond!'?",
      a1: "Woody",
      a2: "Buzz Lightyear",
      a3: "Andy",
      a4: "Sid",
      correct: 2,
    },
  ],
  "Famous Movie Quotes": [
    {
      question:
        "In which movie was the line 'Here's looking at you, kid' said?",
      a1: "*Casablanca*",
      a2: "*Gone with the Wind*",
      a3: "*The Godfather*",
      a4: "*Citizen Kane*",
      correct: 1,
    },
    {
      question:
        "Which movie features the quote 'I feel the need, the need for speed'?",
      a1: "*Top Gun*",
      a2: "*Fast and Furious*",
      a3: "*Die Hard*",
      a4: "*Mission Impossible*",
      correct: 1,
    },
    {
      question:
        "In which film did the character say 'I'm the king of the world!'?",
      a1: "*The Titanic*",
      a2: "*Avatar*",
      a3: "*The Lion King*",
      a4: "*Gladiator*",
      correct: 1,
    },
    {
      question: "Which movie has the line 'You can't handle the truth!'?",
      a1: "*A Few Good Men*",
      a2: "*Scarface*",
      a3: "*The Godfather*",
      a4: "*Pulp Fiction*",
      correct: 1,
    },
    {
      question:
        "In which film is the quote 'I'll have what she's having' featured?",
      a1: "*When Harry Met Sally*",
      a2: "*Pretty Woman*",
      a3: "*The Notebook*",
      a4: "*Sleepless in Seattle*",
      correct: 1,
    },
    {
      question: "Which movie features the line 'Why so serious?'?",
      a1: "*The Dark Knight*",
      a2: "*Batman Begins*",
      a3: "*Joker*",
      a4: "*Suicide Squad*",
      correct: 1,
    },
    {
      question: "What film has the line 'You had me at hello'?",
      a1: "*Jerry Maguire*",
      a2: "*Love Actually*",
      a3: "*The Proposal*",
      a4: "*Notting Hill*",
      correct: 1,
    },
    {
      question:
        "In which movie does the line 'There's no place like home' appear?",
      a1: "*The Wizard of Oz*",
      a2: "*Mary Poppins*",
      a3: "*Peter Pan*",
      a4: "*Alice in Wonderland*",
      correct: 1,
    },
    {
      question: "Which movie features the quote 'I see dead people'?",
      a1: "*The Sixth Sense*",
      a2: "*Ghost*",
      a3: "*Poltergeist*",
      a4: "*Insidious*",
      correct: 1,
    },
    {
      question: "What movie features the quote 'To infinity and beyond!'?",
      a1: "*Finding Nemo*",
      a2: "*Toy Story*",
      a3: "*Wall-E*",
      a4: "*The Incredibles*",
      correct: 2,
    },
  ],
  "Traits" : [
    //Myers-Briggs (3x I vs E, N vs S, F vs T, J vs P)
    {
      question:
        "How do you usually feel after attending a large social event (e.g., a party or group gathering?",
      a1: "Energized and excited",
      a2: "Neutral, I enjoy it, but I don't feel particularly energized or drained",
      a3: "Great! I would stay even longer",
      a4: "Drained, I need to recharge by being alone.",
      answers: {
        a1: "E",
        a2: "",
        a3: "E",
        a4: "I",
      },
    },
    {
      question: "When making decisions, what's more important to you?",
      a1: "Being logical and objective",
      a2: "I like to think about what aligns with my own morals",
      a3: "Both logic and emotions weigh equally in my decisions",
      a4: "Making sure everyone feels heard and understood",
      answers: {
        a1: "T",
        a2: "F",
        a3: "",
        a4: "F",
      },
    },
    {
      question: "What do you value more in discussions?",
      a1: "A balance of practical and abstract ideas",
      a2: "New ideas and creative solutions, even if they aren't immediately practical",
      a3: "Practical advice that can be immediately applied",
      a4: "Useful advice and some abstract ideas too",
      answers: {
        a1: "",
        a2: "N",
        a3: "S",
        a4: "",
      },
    },
    {
      question: "How do you handle unexpected changes in plans?",
      a1: "I find it frustrating and prefer sticking to the original plan",
      a2: "I adapt, but I prefer a set schedule",
      a3: "I enjoy the spontaneity and embrace the change",
      a4: "I adapt easily but prefer to have some structure",
      answers: {
        a1: "J",
        a2: "",
        a3: "P",
        a4: "",
      },
    },
    {
      question: "What do you value more at work or school?",
      a1: "Fostering a harmonious environment, even if it takes extra time",
      a2: "Getting things done efficiently and accurately",
      a3: "Balancing productivity and maintaining a friendly atmosphere",
      a4: "Having things around me to make me feel comfortable",
      answers: {
        a1: "F",
        a2: "T",
        a3: "",
        a4: "F",
      },
    },
    {
      question: "How do you approach planning a vacation?",
      a1: "I like to have a detailed itinerary and plan each step",
      a2: "A backup plan in case my normal plan goes wrong",
      a3: "A general plan works for me, but I like spontaneous moments",
      a4: "I go with the flow and follow my instincts in the moment",
      answers: {
        a1: "S",
        a2: "S",
        a3: "",
        a4: "N",
      },
    },
    {
      question: "How do you prefer to spend your free time?",
      a1: "Going out with friends or meeting new people",
      a2: "Doing something low-key with a close friend or two",
      a3: "Spending time alone with my hobbies or reading",
      a4: "Doing schoolwork or other work",
      answers: {
        a1: "E",
        a2: "",
        a3: "I",
        a4: "I",
      },
    },
    {
      question: "When organizing your day, what's your approach?",
      a1: "I keep a rough plan and stay open to changes",
      a2: "I usually make a list but allow flexibility",
      a3: "I make a to-do list and stick to it",
      a4: "I prefer to go with the flow and see what happens",
      answers: {
        a1: "",
        a2: "",
        a3: "J",
        a4: "P",
      },
    },
    {
      question: "How do you feel about deadlines?",
      a1: "Deadlines are alright, but I need some leeway",
      a2: "I try to stick to them, but don't mind slight flexibility",
      a3: "I prefer sticking to them and working ahead to avoid stress",
      a4: "I like to leave things open-ended and work as inspiration strikes",
      answers: {
        a1: "",
        a2: "",
        a3: "J",
        a4: "P",
      },
    },
    {
      question: "How do you handle conflict?",
      a1: "Ensure that everyone feels respected and understood",
      a2: "I think about a compromise that would resolve tensions",
      a3: "I try to balance logical solutions with empathy",
      a4: "Focus on finding a logical solution, even if it's tough",
      answers: {
        a1: "F",
        a2: "T",
        a3: "",
        a4: "T",
      },
    },
    {
      question:
        "How do you feel about small talk with people you don't know well?",
      a1: "I don't mind it, but I prefer to talk to people I know",
      a2: "I enjoy it and can keep the conversation going",
      a3: "I find it draining and prefer meaningful conversations",
      a4: "It's okay, but I'd rather listen than talk",
      answers: {
        a1: "",
        a2: "E",
        a3: "I",
        a4: "",
      },
    },
    {
      question: "When solving problems, what do you rely on more?",
      a1: "Gut feelings and future possibilities",
      a2: "A mix of intuition and facts",
      a3: "Data, but I consider my instincts too",
      a4: "Facts, data, and past experiences",
      answers: {
        a1: "N",
        a2: "",
        a3: "",
        a4: "S",
      },
    },
  ],
  "Hobbies and Interests": [
    // 5 types of hobbies (physical, intellectual, creative, interactive, technical)
    {
        question: "How do you prefer to spend your weekends?",
        a1: "Exploring new places or trying new activities",
        a2: "Hanging out with friends or family at home",
        a3: "Catching up on personal projects or hobbies",
        a4: "Relaxing with a good book or movie",
        answers: {
            a1: 'Interactive',
            a2: 'Interactive',
            a3: 'Creative',
            a4: 'Creative',
        }
    },    
    {
        question: "What kind of activities do you enjoy the most?",
        a1: "Artistic pursuits like painting, music, or writing",
        a2: "Solving puzzles or working on logical challenges",
        a3: "Participating in workshops or creative classes",
        a4: "Analyzing data or researching topics of interest",
        answers: {
            a1: 'Creative',
            a2: 'Intellectual',
            a3: 'Creative',
            a4: 'Intellectual',
        }
    },
    {
        question: "When it comes to sports or games, what do you prefer?",
        a1: "Playing with a team or in a competitive setting",
        a2: "Playing casually with friends or family",
        a3: "Solo sports or games where I can focus on myself",
        a4: "Participating in cooperative games with friends",
        answers: {
            a1: 'Physical',
            a2: 'Interactive',
            a3: 'Physical',
            a4: 'Interactive',
        }
    },
    {
      question: "What job sounds most appealing to you?",
      a1: "Architect",
      a2: "Lawyer",
      a3: "Interior Designer",
      a4: "Personal Trainer",
      answers: {
        a1: 'Technical',
        a2: 'Interactive',
        a3: 'Creative',
        a4: 'Physical',
    }
    },
    {
      question: "Which magazine would you read",
      a1: "Sports Illustrated",
      a2: "Outdoor Life",
      a3: "Travel & Leisure",
      a4: "Arts & Crafts",
      answers: {
        a1: 'Physical',
        a2: 'Physical',
        a3: 'Interactive',
        a4: 'Creative',
    }
    },
    {
        question: "What type of activities do you find most rewarding?",
        a1: "Volunteering or helping others",
        a2: "Working with new materials",
        a3: "Creating something unique or personal using technology",
        a4: "Engaging in sports or outdoor activities",
        answers: {
            a1: 'Interactive',
            a2: 'Creative',
            a3: 'Technical',
            a4: 'Physical',
        }
    },    
    {
      question: "In the workplace do you prefer to be..",
      a1: "Hands-on, debating with coworkers",
      a2: "Observing patterns to increase efficiency",
      a3: "The Innovator",
      a4: "Everything in between",
      answers: {
        a1: 'Interactive',
        a2: 'Intellectual',
        a3: 'Technical',
        a4: '',
    }
    },
    {
        question: "How do you usually approach learning a new skill?",
        a1: "Jump right in and learn through practice",
        a2: "Research thoroughly before starting",
        a3: "Attend workshops or group classes for hands-on experience",
        a4: "Follow online tutorials or courses at my own pace",
        answers: {
            a1: 'Interactive',
            a2: 'Intellectual',
            a3: 'Interactive',
            a4: 'Technical',
        }
    },
  ],

  "Chemistry Fundamentals": [
    {
      question: "What is the chemical symbol for water?",
      a1: "H2O",
      a2: "O2",
      a3: "CO2",
      a4: "NaCl",
      correct: 1,
    },
    {
      question: "Which element is a noble gas?",
      a1: "Oxygen",
      a2: "Neon",
      a3: "Hydrogen",
      a4: "Nitrogen",
      correct: 2,
    },
    {
      question: "What is the most abundant gas in the Earth's atmosphere?",
      a1: "Oxygen",
      a2: "Carbon Dioxide",
      a3: "Nitrogen",
      a4: "Argon",
      correct: 3,
    },
    {
      question: "What is the pH value of a neutral substance?",
      a1: "0",
      a2: "7",
      a3: "14",
      a4: "1",
      correct: 2,
    },
    {
      question: "Which particle has a negative charge?",
      a1: "Proton",
      a2: "Neutron",
      a3: "Electron",
      a4: "Positron",
      correct: 3,
    },
    {
      question: "What is the atomic number of carbon?",
      a1: "6",
      a2: "8",
      a3: "12",
      a4: "4",
      correct: 1,
    },
    {
      question: "Which compound is also known as table salt?",
      a1: "HCl",
      a2: "NaCl",
      a3: "KCl",
      a4: "MgCl",
      correct: 2,
    },
    {
      question: "Which of these is a metal?",
      a1: "Oxygen",
      a2: "Iron",
      a3: "Helium",
      a4: "Chlorine",
      correct: 2,
    },
    {
      question:
        "What type of bond is formed when electrons are shared between atoms?",
      a1: "Ionic",
      a2: "Covalent",
      a3: "Hydrogen",
      a4: "Van der Waals",
      correct: 2,
    },
    {
      question: "Which chemical element is represented by the symbol 'Au'?",
      a1: "Silver",
      a2: "Gold",
      a3: "Aluminum",
      a4: "Copper",
      correct: 2,
    },
  ],
  "Animal Kingdom": [
    {
      question: "What is the largest land animal?",
      a1: "Elephant",
      a2: "Rhino",
      a3: "Hippo",
      a4: "Giraffe",
      correct: 1,
    },
    {
      question: "Which mammal is known for its ability to fly?",
      a1: "Bat",
      a2: "Squirrel",
      a3: "Flying Lemur",
      a4: "Flying Fox",
      correct: 1,
    },
    {
      question: "What is the fastest land animal?",
      a1: "Cheetah",
      a2: "Lion",
      a3: "Horse",
      a4: "Greyhound",
      correct: 1,
    },
    {
      question: "Which bird is the largest in the world?",
      a1: "Eagle",
      a2: "Penguin",
      a3: "Ostrich",
      a4: "Albatross",
      correct: 3,
    },
    {
      question: "What is the largest species of shark?",
      a1: "Great White Shark",
      a2: "Hammerhead Shark",
      a3: "Whale Shark",
      a4: "Tiger Shark",
      correct: 3,
    },
    {
      question: "Which mammal is known for its impressive memory?",
      a1: "Dolphin",
      a2: "Elephant",
      a3: "Whale",
      a4: "Chimpanzee",
      correct: 2,
    },
    {
      question: "Which of these animals is a marsupial?",
      a1: "Kangaroo",
      a2: "Panda",
      a3: "Elephant",
      a4: "Lion",
      correct: 1,
    },
    {
      question: "What is the tallest animal in the world?",
      a1: "Giraffe",
      a2: "Elephant",
      a3: "Horse",
      a4: "Ostrich",
      correct: 1,
    },
    {
      question: "Which animal is known to have the longest lifespan?",
      a1: "Tortoise",
      a2: "Elephant",
      a3: "Parrot",
      a4: "Blue Whale",
      correct: 1,
    },
    {
      question: "What is the largest species of bird?",
      a1: "Bald Eagle",
      a2: "Condor",
      a3: "Ostrich",
      a4: "Albatross",
      correct: 3,
    },
  ],
  "Space and Astronomy": [
    {
      question: "What is the largest planet in the Solar System?",
      a1: "Earth",
      a2: "Jupiter",
      a3: "Saturn",
      a4: "Neptune",
      correct: 2,
    },
    {
      question: "Which planet is closest to the Sun?",
      a1: "Mercury",
      a2: "Venus",
      a3: "Earth",
      a4: "Mars",
      correct: 1,
    },
    {
      question: "What is the name of Earth's natural satellite?",
      a1: "Moon",
      a2: "Europa",
      a3: "Ganymede",
      a4: "Phobos",
      correct: 1,
    },
    {
      question: "Which planet is known for its rings?",
      a1: "Mars",
      a2: "Jupiter",
      a3: "Uranus",
      a4: "Saturn",
      correct: 4,
    },
    {
      question: "Which galaxy is Earth located in?",
      a1: "Andromeda",
      a2: "Whirlpool",
      a3: "Milky Way",
      a4: "Messier 87",
      correct: 3,
    },
    {
      question: "What is the hottest planet in the Solar System?",
      a1: "Mercury",
      a2: "Venus",
      a3: "Mars",
      a4: "Neptune",
      correct: 2,
    },
    {
      question: "Which planet is known as the Red Planet?",
      a1: "Venus",
      a2: "Mars",
      a3: "Jupiter",
      a4: "Saturn",
      correct: 2,
    },
    {
      question: "What is the closest star to Earth?",
      a1: "Alpha Centauri",
      a2: "Sirius",
      a3: "Sun",
      a4: "Proxima Centauri",
      correct: 3,
    },
    {
      question: "Which planet has the most moons?",
      a1: "Mars",
      a2: "Saturn",
      a3: "Jupiter",
      a4: "Uranus",
      correct: 3,
    },
    {
      question: "What is a light year?",
      a1: "Distance light travels in a year",
      a2: "Time it takes for a star to shine",
      a3: "Age of the universe",
      a4: "Distance between Earth and Sun",
      correct: 1,
    },
  ],
  "Biology" : [
    {
      question: "What is the powerhouse of the cell?",
      a1: "Nucleus",
      a2: "Chloroplast",
      a3: "Mitochondria",
      a4: "Ribosome",
      correct: 3
    },
    {
      question: "Which process is responsible for converting sunlight into chemical energy in plants?",
      a1: "Photosynthesis",
      a2: "Cellular respiration",
      a3: "Fermentation",
      a4: "Transpiration",
      correct: 1
    },
    {
      question: "What type of macromolecule are enzymes?",
      a1: "Carbohydrates",
      a2: "Proteins",
      a3: "Lipids",
      a4: "Nucleic acids",
      correct: 2
    },
    {
      question: "In genetics, what is the term for an organism's physical traits?",
      a1: "Genotype",
      a2: "Phenotype",
      a3: "Allele",
      a4: "Chromosome",
      correct: 2
    },
    {
      question: "Which organ is primarily responsible for filtering blood in humans?",
      a1: "Heart",
      a2: "Liver",
      a3: "Kidney",
      a4: "Lungs",
      correct: 3
    },
    {
      question: "What is the most abundant gas in Earth's atmosphere?",
      a1: "Oxygen",
      a2: "Carbon dioxide",
      a3: "Nitrogen",
      a4: "Hydrogen",
      correct: 3
    },
    {
      question: "Which structure in plant cells is responsible for maintaining turgor pressure?",
      a1: "Cell wall",
      a2: "Vacuole",
      a3: "Chloroplast",
      a4: "Mitochondria",
      correct: 2
    },
    {
      question: "What is the basic unit of life?",
      a1: "Atom",
      a2: "Cell",
      a3: "Molecule",
      a4: "Organ",
      correct: 2
    },
    {
      question: "Which blood cells are responsible for transporting oxygen?",
      a1: "Platelets",
      a2: "White blood cells",
      a3: "Red blood cells",
      a4: "Plasma cells",
      correct: 3
    },
    {
      question: "What is the process by which cells divide to form two identical daughter cells?",
      a1: "Meiosis",
      a2: "Binary fission",
      a3: "Mitosis",
      a4: "Cytokinesis",
      correct: 3
    },
  ], 

  "Foods of the World": [
    {
      question: "Which country is known for sushi?",
      a1: "China",
      a2: "Japan",
      a3: "Thailand",
      a4: "Korea",
      correct: 2,
    },
    {
      question: "Which dish is a traditional Mexican food?",
      a1: "Sushi",
      a2: "Pizza",
      a3: "Tacos",
      a4: "Croissant",
      correct: 3,
    },
    {
      question: "What is the main ingredient in guacamole?",
      a1: "Tomato",
      a2: "Avocado",
      a3: "Cucumber",
      a4: "Pepper",
      correct: 2,
    },
    {
      question:
        "Which spice is commonly used in Indian cuisine and is known for its yellow color?",
      a1: "Paprika",
      a2: "Turmeric",
      a3: "Cumin",
      a4: "Coriander",
      correct: 2,
    },
    {
      question:
        "Which dish is a traditional Italian pasta dish with a meat sauce?",
      a1: "Fettuccine Alfredo",
      a2: "Spaghetti Bolognese",
      a3: "Lasagna",
      a4: "Carbonara",
      correct: 2,
    },
    {
      question: "What type of bread is traditionally used in a falafel wrap?",
      a1: "Pita",
      a2: "Naan",
      a3: "Baguette",
      a4: "Tortilla",
      correct: 1,
    },
    {
      question:
        "Which country is famous for its chocolate, particularly from the city of Zurich?",
      a1: "Belgium",
      a2: "France",
      a3: "Switzerland",
      a4: "Germany",
      correct: 3,
    },
    {
      question: "What is the main ingredient in hummus?",
      a1: "Chickpeas",
      a2: "Lentils",
      a3: "Beans",
      a4: "Rice",
      correct: 1,
    },
    {
      question:
        "Which fruit is known as the 'king of fruits' and is notorious for its strong smell?",
      a1: "Durian",
      a2: "Mango",
      a3: "Pineapple",
      a4: "Papaya",
      correct: 1,
    },
    {
      question:
        "What is the traditional Russian beverage made from fermented bread?",
      a1: "Vodka",
      a2: "Kvass",
      a3: "Kompot",
      a4: "Medovukha",
      correct: 2,
    },
  ],
};
