export const subData =
[
    {
        title: 'Basketball',
        backgroundImage: 'https://img.freepik.com/free-vector/gradient-dynamic-blue-lines-background_23-2148995756.jpg',
        category: 'Sports',
        desc: "Are you a basketball pro? Show off your knowledge of players, teams, and championships.",
    },
    {
        title: 'Famous Wars',
        backgroundImage: 'https://img.freepik.com/free-vector/gradient-dynamic-blue-lines-background_23-2148995756.jpg',
        category: 'History',
        desc: "Dive into the details of major conflicts and the events that defined them.",
    },
    {
        title: 'Soccer Facts',
        backgroundImage: 'https://img.freepik.com/free-vector/gradient-dynamic-blue-lines-background_23-2148995756.jpg',
        category: 'Sports',
        desc: "From the World Cup to club leagues, test your soccer knowledge.",
    },
    {
        title: 'Countries of the World',
        backgroundImage: 'https://img.freepik.com/free-vector/gradient-dynamic-blue-lines-background_23-2148995756.jpg',
        category: 'Geography',
        desc: "Can you name the nations of the world? Test your geography skills here.",
    },
    {
        title: 'Historical Figures',
        backgroundImage: 'https://img.freepik.com/free-vector/gradient-dynamic-blue-lines-background_23-2148995756.jpg',
        category: 'History',
        desc: "Learn about the people who shaped history and left their mark on the world.",
    },
    {
        title: 'American Football',
        backgroundImage: 'https://img.freepik.com/free-vector/gradient-dynamic-blue-lines-background_23-2148995756.jpg',
        category: 'Sports',
        desc:"How well do you know the NFL teams, players, and records?",
    },
    {
        title: 'US History',
        backgroundImage: 'https://img.freepik.com/free-vector/gradient-dynamic-blue-lines-background_23-2148995756.jpg',
        category: 'History',
        desc: "From the Revolutionary War to the modern era, test your knowledge of American history.",
    },
    {
        title: 'Movie Characters',
        backgroundImage: 'https://img.freepik.com/free-vector/gradient-dynamic-blue-lines-background_23-2148995756.jpg',
        category: 'Movies',
        desc:  "Test your memory of iconic characters from the silver screen.",
    },
    {
        title: 'Chemistry Fundamentals',
        backgroundImage: 'https://img.freepik.com/free-vector/gradient-dynamic-blue-lines-background_23-2148995756.jpg',
        category: 'Science',
        desc: "From the periodic table to chemical reactions, see how much you know about chemistry.",
    },
    {
        title: 'Animal Kingdom',
        backgroundImage: 'https://img.freepik.com/free-vector/gradient-dynamic-blue-lines-background_23-2148995756.jpg',
        category: 'Science',
        desc: "Learn about the fascinating creatures that share our planet.",
    },
    {
        title: 'Space and Astronomy',
        backgroundImage: 'https://img.freepik.com/free-vector/gradient-dynamic-blue-lines-background_23-2148995756.jpg',
        category: 'Science',
        desc: "Explore the stars, planets, and mysteries of the cosmos.",
    },
    {
        title: 'Traits',
        backgroundImage: 'https://img.freepik.com/free-vector/gradient-dynamic-blue-lines-background_23-2148995756.jpg',
        category: 'Personality',
        desc: "Explore your personality traits with quizzes about how you think and feel.",
    },
    {
        title: 'Famous Movie Quotes',
        backgroundImage: 'https://img.freepik.com/free-vector/gradient-dynamic-blue-lines-background_23-2148995756.jpg',
        category: 'Movies',
        desc:"Can you match the quote to the movie? Put your movie knowledge to the test!", 
    },
    {
        title: 'Bands and Artists',
        backgroundImage: 'https://img.freepik.com/free-vector/gradient-dynamic-blue-lines-background_23-2148995756.jpg',
        category: 'Music',
        desc: "From legends to modern stars, test your knowledge of the music world's greats.",
    },
    {
        title: 'Foods of the World',
        backgroundImage: 'https://img.freepik.com/free-vector/gradient-dynamic-blue-lines-background_23-2148995756.jpg',
        category: 'Misc',
        desc:"Are you a foodie? Test your knowledge of dishes, ingredients, and cuisines.", 
    },
    {
        title: 'Hobbies and Interests',
        backgroundImage: 'https://img.freepik.com/free-vector/gradient-dynamic-blue-lines-background_23-2148995756.jpg',
        category: 'Personality',
        desc: "Discover new hobbies or learn more about your current passions.",
    },
    {
        title: 'Biology',
        backgroundImage: 'https://img.freepik.com/free-vector/gradient-dynamic-blue-lines-background_23-2148995756.jpg',
        category: 'Science',
        desc: "Dive into the study of life, from cells to ecosystems.", 
    },
];